In [1]:
# import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# read the data

df = pd.read_csv('/Users/gnanreddybobba/Desktop/bank+marketing/bank-additional/bank-additional-full.csv', sep=';')

In [6]:
# check the data

df.head(10)

age          job  marital            education  default housing loan  \
0   56    housemaid  married             basic.4y       no      no   no   
1   57     services  married          high.school  unknown      no   no   
2   37     services  married          high.school       no     yes   no   
3   40       admin.  married             basic.6y       no      no   no   
4   56     services  married          high.school       no      no  yes   
5   45     services  married             basic.9y  unknown      no   no   
6   59       admin.  married  professional.course       no      no   no   
7   41  blue-collar  married              unknown  unknown      no   no   
8   24   technician   single  professional.course       no     yes   no   
9   25     services   single          high.school       no     yes   no   

     contact month day_of_week  ...  campaign  pdays  previous     poutcome  \
0  telephone   may         mon  ...         1    999         0  nonexistent   
1  telephone   may         mon  ...         1    999         0  nonexistent   
2  telephone   may         mon  ...         1    999         0  nonexistent   
3  telephone   may         mon  ...         1    999         0  nonexistent   
4  telephone   may         mon  ...         1    999         0  nonexistent   
5  telephone   may         mon  ...         1    999         0  nonexistent   
6  telephone   may         mon  ...         1    999         0  nonexistent   
7  telephone   may         mon  ...         1    999         0  nonexistent   
8  telephone   may         mon  ...         1    999         0  nonexistent   
9  telephone   may         mon  ...         1    999         0  nonexistent   

  emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          1.1          93.994          -36.4      4.857       5191.0  no  
1          1.1          93.994          -36.4      4.857       5191.0  no  
2          1.1          93.994          -36.4      4.857       5191.0  no  
3          1.1          93.994          -36.4      4.857       5191.0  no  
4          1.1          93.994          -36.4      4.857       5191.0  no  
5          1.1          93.994          -36.4      4.857       5191.0  no  
6          1.1          93.994          -36.4      4.857       5191.0  no  
7          1.1          93.994          -36.4      4.857       5191.0  no  
8          1.1          93.994          -36.4      4.857       5191.0  no  
9          1.1          93.994          -36.4      4.857       5191.0  no  

[10 rows x 21 columns]

In [7]:
# info of the data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             41188 non-null  int64  
 1   job             41188 non-null  object 
 2   marital         41188 non-null  object 
 3   education       41188 non-null  object 
 4   default         41188 non-null  object 
 5   housing         41188 non-null  object 
 6   loan            41188 non-null  object 
 7   contact         41188 non-null  object 
 8   month           41188 non-null  object 
 9   day_of_week     41188 non-null  object 
 10  duration        41188 non-null  int64  
 11  campaign        41188 non-null  int64  
 12  pdays           41188 non-null  int64  
 13  previous        41188 non-null  int64  
 14  poutcome        41188 non-null  object 
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null 

In [8]:
# check the missing values

df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [9]:
# check the data types

df.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [10]:
# check the shape of the data

df.shape

(41188, 21)

In [11]:
# drop the duration coloumn

df.drop('duration', axis=1, inplace=True)

In [12]:
# encode the target variable(y) to 0 and 1

df['y'] = df['y'].map({'no': 0, 'yes': 1})

In [14]:
# label encode all the categorical variables

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_columns = df.select_dtypes(include='object').columns.tolist()

for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [15]:
# verify the data types

df.dtypes

age                 int64
job                 int64
marital             int64
education           int64
default             int64
housing             int64
loan                int64
contact             int64
month               int64
day_of_week         int64
campaign            int64
pdays               int64
previous            int64
poutcome            int64
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                   int64
dtype: object

In [16]:
# train-test split

from sklearn.model_selection import train_test_split

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
# train the decision tree model

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [18]:
# model evaluation

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred = dt.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred))

print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))

print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy: 0.8316338917212915
Confusion Matrix:
 [[6538  765]
 [ 622  313]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.90      7303
           1       0.29      0.33      0.31       935

    accuracy                           0.83      8238
   macro avg       0.60      0.62      0.61      8238
weighted avg       0.84      0.83      0.84      8238



In [19]:
# handle the class imbalance

from sklearn.tree import DecisionTreeClassifier

# Re-initialize model with class_weight='balanced'
dt_model_balanced = DecisionTreeClassifier(class_weight='balanced', random_state=42)

# Train the new model
dt_model_balanced.fit(X_train, y_train)

# Predict
y_pred_balanced = dt_model_balanced.predict(X_test)

# Evaluate again
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_balanced))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_balanced))
print("Classification Report:\n", classification_report(y_test, y_pred_balanced))


Accuracy: 0.8403738771546492
Confusion Matrix:
 [[6608  695]
 [ 620  315]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.91      7303
           1       0.31      0.34      0.32       935

    accuracy                           0.84      8238
   macro avg       0.61      0.62      0.62      8238
weighted avg       0.85      0.84      0.84      8238



In [20]:
# train the random forest model

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()

rf.fit(X_train, y_train)

RandomForestClassifier()

In [21]:
# model evaluation of random forest

y_pred_rf = rf.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_balanced))
print("Classification Report:\n", classification_report(y_test, y_pred_balanced))

Accuracy: 0.8928137897547949
Confusion Matrix:
 [[6608  695]
 [ 620  315]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.90      0.91      7303
           1       0.31      0.34      0.32       935

    accuracy                           0.84      8238
   macro avg       0.61      0.62      0.62      8238
weighted avg       0.85      0.84      0.84      8238



In [22]:
# train xgboost model

from xgboost import XGBClassifier

xgb = XGBClassifier()

xgb.fit(X_train, y_train)

ModuleNotFoundError: No module named 'xgboost'

In [23]:
!pip install xgboost

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 623.3 kB/s eta 0:00:0000:0100:01


In [24]:
!pip3 install xgboost

In [25]:
# train the xgboost model

from xgboost import XGBClassifier

xgb = XGBClassifier()

xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [26]:
# model evaluation of xgboost

y_pred_xgb = xgb.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))

Accuracy: 0.8956057295460063
Confusion Matrix:
 [[7107  196]
 [ 664  271]]
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94      7303
           1       0.58      0.29      0.39       935

    accuracy                           0.90      8238
   macro avg       0.75      0.63      0.66      8238
weighted avg       0.88      0.90      0.88      8238



In [27]:
# train the xgboost model with class imbalance

from xgboost import XGBClassifier

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', scale_pos_weight=4, random_state=42)

xgb.fit(X_train, y_train)

/opt/anaconda3/lib/python3.11/site-packages/xgboost/training.py:183: UserWarning: [16:21:51] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [28]:
# model evaluation of xgboost with class imbalance

y_pred_xgb = xgb.predict(X_test)

print('Accuracy:', accuracy_score(y_test, y_pred_xgb))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_xgb))
print("Classification Report:\n", classification_report(y_test, y_pred_xgb))

Accuracy: 0.8755765962612284
Confusion Matrix:
 [[6763  540]
 [ 485  450]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93      7303
           1       0.45      0.48      0.47       935

    accuracy                           0.88      8238
   macro avg       0.69      0.70      0.70      8238
weighted avg       0.88      0.88      0.88      8238



In [29]:
# save the trained xgboost model

import joblib

joblib.dump(xgb, 'xgboost_model.pkl')

['xgboost_model.pkl']

In [30]:
# load the saved model

model = joblib.load('xgboost_model.pkl')

# predict using the loaded model

y_pred = model.predict(X_test)

# model evaluation of the loaded model

print('Accuracy:', accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))  
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8755765962612284
Confusion Matrix:
 [[6763  540]
 [ 485  450]]
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93      7303
           1       0.45      0.48      0.47       935

    accuracy                           0.88      8238
   macro avg       0.69      0.70      0.70      8238
weighted avg       0.88      0.88      0.88      8238

